# Generated by Django 4.1 on 2023-06-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_spot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
